import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header";
import { Noto_Serif_JP } from "next/font/google";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

const NotoSerifJP = Noto_Serif_JP({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-NotoSerifJP",
});

export const metadata: Metadata = {
  title: "創作",
  icons: '/image/favicon.ico',
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NotoSerifJP.variable} font-NotoSerifJP`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
